### ISSUE TITLE
Question about auth service

### ISSUE THREAD

**Issue by talamaska** [SekibOmazic/ngrx-auth-example#3]
I have some questions. I looked at your code, in my mind async actions should be described as effects. But you don't have effects. Is this AuthService playing the role of effects in your project?

**Comment by SekibOmazic** [comment]
Yes, my AuthService is the place where I put all actions that cause side effects. At the time I wrote the example there was no ngrx/effects ;-)

**Comment by talamaska** [comment]
ok. thanks for the quick answer.
